export default function Page() {
  return (
    <main className="flex min-h-screen items-center justify-center">
      <div className="text-center">
        <h1 className="text-2xl font-bold">Hello vSeek!</h1>
        <p className="text-muted-foreground mt-2">
          This page was generated by vSeek Studio.
        </p>
      </div>
    </main>
  );
}
